# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/141uGU5pdrbNhyQFjkqcpdvaORIJ01jK8
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6])
y=np.array([0,250])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,2,6,8,10,12])
y=np.array([3,5,2,6,4,7])
plt.plot(x,y,marker='o',ms=20,mec='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([1,2,4,6,8])
y1=np.array([2,7,3,6,5])
x2=np.array([3,5,7,9,11])
y2=np.array([7,2,5,3,6])
plt.plot(x1,y1,x2,y2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,0,0,0,2,2,4,4,4,4])
y=np.array([0,10,20,30,0,30,0,10,20,30])
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,5,7,2,4,6])
y=np.array([3,5,8,1,6,4])
plt.scatter(x,y,color='orange')
x=np.array([7,9,2,6,4,5])
y=np.array([3,6,7,5,1,9])
plt.scatter(x,y,color='blue')
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3,4,5])
y=np.array([0,2,8,1,14,7])
mycolor=['red','green','purple','lime','aqua','yellow']
size=[10,60,120,140,160,180]
plt.scatter(x,y,color=mycolor,s=size)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['A','B','C','D'])
y=np.array([3,8,1,10])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['A','B','C','D'])
y=np.array([3,8,1,10])
plt.barh(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['A','B','C','D'])
y=np.array([3,8,1,10])
plt.bar(x,y,width=0.1)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
plt.pie(x)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylabels=["Apple","Bananas","Cherries","Dates"]
plt.pie(x,labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylabels=["Apple","Bananas","Cherries","Dates"]
plt.pie(x,labels=mylabels,startangle=90)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylabels=["Apple","Bananas","Cherries","Dates"]
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylabels,startangle=90,explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylabels=["Apple","Bananas","Cherries","Dates"]
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylabels,startangle=90,explode=myexplode,shadow=True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mycolors=["black","hotpink","b","yellow"]
mylabels=["Apple","Bananas","Cherries","Dates"]
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylabels,startangle=90,explode=myexplode,shadow=True,colors=mycolors)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylabels=["Apple","Bananas","Cherries","Dates"]
plt.pie(x,labels=mylabels)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylabels=["Apple","Bananas","Cherries","Dates"]
plt.pie(x,labels=mylabels)
plt.legend(title='Four Fruits:')
plt.show()